ktor:
  deployment:
    port: 8081
  application:
    modules:
      - com.hackathon.summer.faf.ApplicationKt.module

database:
  jdbcUrl: "jdbc:postgresql://postgres:5432/beach_db"
  driverClassName: "org.postgresql.Driver"
  username: "user"
  password: "password"
  maximumPoolSize: 10